import prisma from "@/lib/db";
import { protectedProcedure, createTRPCRouter } from "@/trpc/init";
import { Client } from "@notionhq/client";
import z from "zod";

export const integrationsRouter = createTRPCRouter({
 getNotionDatabases:
  protectedProcedure.query(async ({ ctx }) => {

    const integration =
      await prisma.integration.findFirst({
        where: {
          userId: ctx.auth.user.id,
          provider: "notion",
        },
      });

    if (!integration) {
      throw new Error(
        "Notion not connected"
      );
    }

    const notion = new Client({
      auth: integration.accessToken,
    });

    let response =
      await notion.search({
        filter: {
          property: "object",
          value: "data_source",
        },
      });

    let databaseId = "";

    // no database found
    if (response.results.length === 0) {

      const pages =
        await notion.search({
          filter: {
            property: "object",
            value: "page",
          },
        });

      const firstPage =
        pages.results[0];

      if (!firstPage) {
        throw new Error(
          "No accessible page found"
        );
      }

      const database =
        await notion.databases.create({

          parent: {
            type: "page_id",
            page_id: firstPage.id,
          },

          title: [
            {
              type: "text",
              text: {
                content:
                  "AI Automation Database",
              },
            },
          ],

          initial_data_source: {

            properties: {

              Name: {
                title: {},
              },

              Content: {
                rich_text: {},
              },

              CreatedAt: {
                date: {},
              },

            },
          },
        });

      console.log(
        "Created database:",
        database
      );

      databaseId = database.id;

      // refetch
      response =
        await notion.search({
          filter: {
            property: "object",
            value: "data_source",
          },
        });

    } else {

      databaseId =
        response.results[0].id;
    }

    // create page
    await notion.pages.create({

      parent: {
        data_source_id:
          databaseId,
      },

      properties: {

        Name: {
          title: [
            {
              text: {
                content:
                  "AI Generated Blog",
              },
            },
          ],
        },

        Content: {
          rich_text: [
            {
              text: {
                content:
                  "This blog was generated by AI",
              },
            },
          ],
        },

        CreatedAt: {
          date: {
            start:
              new Date().toISOString(),
          },
        },

      },
    });

    const databases =
      response.results.map((db: any) => ({
        id: db.id,

        title:
          db.title?.[0]?.plain_text ||
          "Untitled Database",
      }));

    return {
      success: true,
      databases,
    };
  }),
  // Implementation for creating an integration
})